Dev 1.12 - translate content/ko/docs/tutorials/hello-minikube.md
kubernetes/kubernetes-docs-ko pull request #18
Opened 2018-08-27 12:04 UTC by lawlait

translate content/ko/docs/tutorials/hello-minikube.md

Hello Minikube 에 대한 번역 초안 입니다.
여러가지 고민해야할 사항이 있어서 회의 참석해서 확인 후에 수정하도록 하겠습니다.

2018-08-27 12:26 UTC, gochist commented
PR 감사드립니다! 아래 참고해서 CLA 제출 부탁드립니다. 

> Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

2018-08-27 12:57 UTC, gochist requested changes
PR 감사드립니다! 부족하지만 몇 가지 커맨트드립니다. 의견 또는 반영 부탁드립니다.

2018-08-27 12:57 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
s/어플리케이션/애플리케이션/
> [국립국어원에서 애플리케이션으로 심의했다고 합니다.](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=60&qna_seq=129811&pageIndex=1)

2018-08-27 12:57 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
s/Node.js 로/Node.js로/
s/Minikube 에서/Minikube에서/
> 영단어라도 조사는 붙여쓰는 것이 맞다고 알고 있습니다. 일괄 적용 부탁드립니다.

2018-08-27 12:57 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
s/변환 한/변환한/

2018-08-27 12:57 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
이 부분은 옵션입니다. 원문이 가로 폭을 맞추기 위해 강제 개행한 경우, 번역본도 가로 폭을 맞추어 개행해 주어야 원문 문서와 변경 내역 추적이 조금 더 수월해집니다.

2018-08-27 12:57 UTC, gochist commented
본 PR의 Merge 여부와 무관하게, 번역 문체에 대한 논의가 없었는데, 경어체를 써야할지 말아야할지 논의해볼 필요가 있을 것 같습니다.

2018-08-28 02:31 UTC, gochist reviewed
/lgtm

2018-08-28 03:07 UTC, gochist approved these changes

2018-08-28 03:08 UTC, gochist commented
승인 여부 판단 부탁드립니다.
/assign @ClaudiaJKang

2018-08-28 04:23 UTC, claudiajkang commented on content/ko/docs/tutorials/hello-minikube.md
> +애플리케이션으로 변환하는 것 입니다.튜토리얼을 통해 로컬에서 작성된 코드를 Docker 컨테이너 이미지로
`변환하는 것 입니다.튜토리얼을` 에서 마침표 이후 공백이 추가되어야 할 듯 합니다.

2018-08-28 04:30 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +애플리케이션으로 변환하는 것 입니다.튜토리얼을 통해 로컬에서 작성된 코드를 Docker 컨테이너 이미지로
`your machine`이 `로컬`로 번역하신 것 같은데 `machine`이라는 단어가 [2018-08-28 kubernetes-docs-ko 주간 회의](https://goo.gl/1gZ45u)에서 용어집 업데이트가 이루어 질 예정이므로, 회의 이후 수정이 필요할 것 같습니다.

2018-08-28 04:36 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +애플리케이션으로 변환하는 것 입니다.튜토리얼을 통해 로컬에서 작성된 코드를 Docker 컨테이너 이미지로
원문이 `a simple Hello World Node.js app`이기 때문에,
`간단한 Node.js 로 작성된 Hello World 애플리케이션을` 보다 `Node.js로 작성된 간단한 Hello World 애플리케이션을`으로 하는 것이 좋을 것 같습니다.

2018-08-28 04:38 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +방법을 보여줍니다. Minikube는 무료로 로컬 기기를 이용해서 쿠버네티스를 실행할 수 있는 간단한 방법을
위에서는 `your machine`을 `로컬`로 번역하셨는데, 
현재의 경우 `your local machine`을 `로컬 기기`로 번역이 되어있습니다. 

위에서 언급한 동일한 이유로 용어 통일이 필요할 것 같습니다.

2018-08-28 04:40 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
위의 경우 #16 의 경우 문장으로 번역되었고, 현재의 경우 단어로 번역이 되었기 때문에 이 부분도 통일이 필요합니다. 
@gochist 의견 부탁드립니다.

2018-08-28 04:53 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +프록시를 거치지않고 직접 https://cloud.google.com/container-registry/ 같은 사이트에 액세스 할 수 있는지 확인하려면 새 터미널을 열고 다음과 같이 실행하십시오.
`https://cloud.google.com/container-registry/`의 경우 원문 링크 추가가 필요합니다.

2018-08-28 04:54 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +  **Note:** macOS 10.13 버전으로 업데이트 후 Homebrew에서 `brew update` 를 실행 시 다음과 같은 오류가 발생할 경우:
`Note` 번역이 필요합니다!

2018-08-28 05:05 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +  **Note:** macOS 10.13 버전으로 업데이트 후 Homebrew에서 `brew update` 를 실행 시 다음과 같은 오류가 발생할 경우:
`brew update` 를 -> `brew update`를 
수정이 필요합니다.

2018-08-28 05:08 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +## Minikube 클러스터 만들기
`만들기` -> `생성하기`는 어떠신가요?

2018-08-28 05:09 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +로컬 클러스터를 만듭니다. 이 튜토리얼에서는 macOS에서
`만듭니다.`의 경우 위에서 결정된 내용대로 수정이 필요할 것 같습니다.

2018-08-28 05:10 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +사용한다고 가정하였습니다. Docker for Mac 대신 Linux 혹은 VirtualBox 와 같이 다른 플랫폼을
`VirtualBox 와` -> `VirtualBox와` 수정이 필요합니다.

2018-08-28 05:10 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +사용하는 경우, Minikube 를 설치하는 방법이 약간 다를 수 있습니다. 일반적인 Minikube 설치 지침은
`Minikube 를` -> `Minikube를`으로 수정이 필요합니다.

2018-08-28 05:19 UTC, claudiajkang commented on content/ko/docs/tutorials/hello-minikube.md
> +프록시를 거치지않고 직접 https://cloud.google.com/container-registry/ 같은 사이트에 액세스 할 수 있는지 확인하려면 새 터미널을 열고 다음과 같이 실행하십시오.
`액세스`의 경우도 [2018-08-28 kubernetes-docs-ko 주간 회의](https://goo.gl/1gZ45u)에서 용어집 업데이트가 이루어 질 예정이므로, 회의 이후 수정이 필요할 것 같습니다.

2018-08-28 05:22 UTC, claudiajkang commented on content/ko/docs/tutorials/hello-minikube.md
> +Docker 데몬이 시작되었는지 확인하십시오. Docker가 실행 중인지는 다음과 같은 커맨드를 사용하여 확인:
`커맨드`의 경우도 [2018-08-28 kubernetes-docs-ko 주간 회의](https://goo.gl/1gZ45u)에서 용어집 업데이트가 이루어 질 예정이므로, 회의 이후 수정이 필요할 것 같습니다.

2018-08-28 05:28 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +프록시가 필요한 경우, 다음 방법을 사용하여 프록시 설정으로 Minikube 클러스터를 시작:
원문이 `to start Minikube cluster with proxy setting`이므로 
`프록시 설정으로 Minikube 클러스터를 시작`보다 `프록시 설정과 함께 Minikube 클러스터를 시작`이 알맞은 것 같습니다.

2018-08-28 05:30 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +명시된 `--vm-driver = hyperkit` 플래그는 Docker for Mac을 사용하고 있음을 의미합니다.
`--vm-driver = hyperkit` 부분의 경우 명령이기 때문에 원문 `--vm-driver=hyperkit` 유지가 필요합니다.

2018-08-28 05:35 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +명시된 `--vm-driver = hyperkit` 플래그는 Docker for Mac을 사용하고 있음을 의미합니다.
명시된 `--vm-driver = hyperkit` 플래그는 Docker for Mac을 사용하고 있음을 의미합니다. 

위의 문장의 경우 아래 두 가지의 경우로 `명시된`이라는 의미를 빼고 동사 의미를 정의하는 것이 좋을 듯 합니다. 
1) `--vm-driver = hyperkit` 플래그는 Docker for Mac을 사용하고 있음을 의미합니다. 
2) `--vm-driver = hyperkit` 플래그는 Docker for Mac을 사용하고 있음을 명시합니다.

2018-08-28 05:36 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +이제 Minikube 컨텍스트를 설정하십시오. 컨텍스트는 `kubectl` 과 상호 작용하는
`컨텍스트`의 경우도 [2018-08-28 kubernetes-docs-ko 주간 회의](https://goo.gl/1gZ45u)에서 용어집 업데이트가 이루어 질 예정이므로, 회의 이후 수정이 필요할 것 같습니다.

2018-08-28 05:39 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +`kubectl` 이 클러스터와 통신할 수 있도록 설정되어 있는지 확인:
`kubectl` 이 -> ``kubectl`이
수정이 필요합니다.

2018-08-28 05:41 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +`kubectl` 이 클러스터와 통신할 수 있도록 설정되어 있는지 확인:
`configured`와 `setting` 모두 설정으로 번역되었는데 이 부분에 대한 검토가 필요합니다. @gochist @ianychoi

2018-08-28 05:43 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +## Node.js 애플리케이션 만들기
`만들기`의 경우 위에서(line 55) 결정된 내용대로 수정이 필요할 것 같습니다.

2018-08-28 05:45 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +`server.js` 라는 이름으로 저장:
`server.js` 라는 -> `server.js`라는

수정이 필요합니다.

2018-08-28 05:47 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +http://localhost:8080/ 에 접속하여 "Hello World!" 라는 메세지를 확인 할 수 있습니다.
http://localhost:8080/ 에 -> http://localhost:8080/에
"Hello World!" 라는 -> "Hello World!"라는

수정이 필요합니다.

2018-08-28 05:50 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +Node.js 서버를 중단하려면 **Ctrl-C** 를 입력합니다.
*Ctrl-C** 를 -> *Ctrl-C**를 
수정이 필요합니다.

2018-08-28 05:52 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +Node.js 서버를 중단하려면 **Ctrl-C** 를 입력합니다.
원문이 Stoop the running Node.js server by pressing **Ctrl-C**. 이기 때문에 

Node.js 서버를 중단하려면 **Ctrl-C**를 입력합니다. 

보다 아래 두 가지의 경우로 번역하는 것이 좋을 것 같습니다. 
1) **Ctrl-C**를 입력하면 실행 중인 Node.js 서버가 중단합니다. 
2) **Ctrl-C**를 입력하면 실행 중인 Node.js 서버가 정지합니다.

2018-08-28 05:55 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +작성된 애플리케이션 실행:
아래 line 143 `The next step is to package your application in a Docker container.` 문장에서도 `다음 단계는 작성된 애플리케이션을 Docker 컨테이너로 변환해봅니다.`로 번역하셨기 때문에 

`your application`을 `작성된 애플리케이션`으로 번역을 하는 것이 맞는지 모르겠습니다. @gochist @ianychoi

2018-08-28 05:56 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +다음 단계는 작성된 애플리케이션을 Docker 컨테이너로 변환해봅니다.
line 133 리뷰 내용을 바탕으로 수정이 필요합니다.

2018-08-28 05:58 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +## Docker 컨테이너 이미지 만들기
`만들기`의 경우 위에서(line 55) 결정된 내용대로 수정이 필요할 것 같습니다.

2018-08-28 05:59 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +앞에서 사용하였던 `hellonode` 폴더에  `Dockerfile` 이라는 이름으로 파일을 만듭니다. Dockerfile
`만듭니다`의 경우 위에서(line 55) 결정된 내용대로 수정이 필요할 것 같습니다.

2018-08-28 06:00 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +은 작성하고자하는 이미지에 대한 구성요소를 미리 설정해놓은 파일입니다. 기존 이미지를 확장하여 Docker
`작성하고자하는` -> `작성하고자 하는`으로 수정이 필요합니다.

2018-08-28 06:01 UTC, ClaudiaJKang commented
/hold

2018-08-28 06:13 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/hello-minikube.md
> +은 작성하고자하는 이미지에 대한 구성요소를 미리 설정해놓은 파일입니다. 기존 이미지를 확장하여 Docker
`A Dockerfile describes
the image that you want to build.` -> `Dockerfile은 작성하고자하는 이미지에 대한 구성요소를 미리 설정해놓은 파일입니다.`

제 생각에는 너무 많은 의역이 된 것 같습니다. @gochist @ianychoi 리뷰 부탁드립니다.

2018-08-28 06:24 UTC, claudiajkang commented
@lawlait 148 line까지 리뷰 완료했습니다. 본의아니게 알림 테러를 했네요.. 죄송합니다.. 
148 line 이후 리뷰는 오늘 회의 진행 이후 진행하도록 하겠습니다.

2018-08-28 08:24 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
> +## Minikube 클러스터 만들기
일관성을 맞추면 더 좋겠지만, 이대로도 괜찮습니다. 참고해주세요.

2018-08-28 08:34 UTC, zer0big commented on content/ko/docs/tutorials/hello-minikube.md
> +이제 Minikube 컨텍스트를 설정하십시오. 컨텍스트는 `kubectl` 과 상호 작용하는
The context is what determines which cluster `kubectl` is interacting with. 의 해석을
"컨텍스트는 'kubectl' 이 어떠한 클러스터와 상호작용 하려고 하는지를  결정한 내용입니다."  로 하심이 어떨지 검토 요청 드립니다.

2018-08-28 08:37 UTC, zer0big commented on content/ko/docs/tutorials/hello-minikube.md
> +http://localhost:8080/ 에 접속하여 "Hello World!" 라는 메세지를 확인 할 수 있습니다.
You should be able to see ... 결과에 대한 검증 확인 방법을 제시하는 문장이므로
" 확인할 수 있어야(만) 합니다." 라고 처리하심이 어떨지 검토 부탁 드립니다.

2018-08-28 08:40 UTC, zer0big commented on content/ko/docs/tutorials/hello-minikube.md
> +Node.js 서버를 중단하려면 **Ctrl-C** 를 입력합니다.
by pressing **Ctrl-C**... by ~ing 문장 구조이므로, ~ 함으로써의 의미를 살리고 서버 정지에 대한 방법을 제시하는 상황이므로  "Ctrl+C"를 눌러" 는 어떨지요~?

2018-08-28 08:43 UTC, gochist commented
@lawlait 이제 시작이라 아직 리뷰 기준이 미흡한 부분이 많고, 조금 더 합의가 되어야 할 내용도 많은 상태임을 이해부탁드립니다. 
@ClaudiaJKang @zer0big 꼼꼼한 리뷰에 감사드립니다! 다만 어느 정도 합의된 기준이 있는 건들 위주로 리뷰하고, 그렇지 않은 부분은 컨트리뷰터의 스타일을 존중하는 것도 좋을 것 같습니다. 문서는 앞으로도 계속 고칠 수 있습니다.

2018-08-28 08:50 UTC, zer0big commented
@gochist 공식적인 문서가 될 것이고 최대한 정확한 의미전달을 위해 꼼꼼한 리뷰가 필요하다고 생각되어 의견을 제시해 본다는 것이... 스타일에 대한 존중 부분에 의도와 달리 전달되었다면 양해바랍니다. 객관적인 기준을 근거로 함께 좋은 결과을 이루어 가자는 배경에서 리뷰활동 열심히 하고자합니다. 이후 추가 리뷰 커맨트를 남길때 저도 참고하겠습니다~^

2018-09-03 02:26 UTC, lawlait commented on content/ko/docs/tutorials/hello-minikube.md
> +http://localhost:8080/ 에 접속하여 "Hello World!" 라는 메세지를 확인 할 수 있습니다.
댓글에서도 확인 가능한 부분이지만, http://localhost:8080/에 로 하는 경우 자동으로 생성되는 링크에 오류가 발생되고, 원문에서 링크를 지정하지 않았기 때문에 따로 작성하지 않은 부분입니다. 
@gochist @ClaudiaJKang 확인 부탁드립니다.

2018-09-03 02:28 UTC, lawlait commented on content/ko/docs/tutorials/hello-minikube.md
> +Node.js 서버를 중단하려면 **Ctrl-C** 를 입력합니다.
이 부분도 "**Ctrl-C**를" 의 경우, Markdown 상에서 오류가 발생되는 사항입니다.
오류를 무시하고 그대로 지정할 것인지 확인 부탁드립니다.

2018-09-03 02:30 UTC, lawlait commented on content/ko/docs/tutorials/hello-minikube.md
> +작성된 애플리케이션 실행:
"원문의 감성 그대로" 라고 정해지기 전이라 약간의 의역을 포함하였던 부분인데, "애플리케이션 실행" 으로 변경합니다.

2018-09-03 02:34 UTC, lawlait commented on content/ko/docs/tutorials/hello-minikube.md
> +은 작성하고자하는 이미지에 대한 구성요소를 미리 설정해놓은 파일입니다. 기존 이미지를 확장하여 Docker
위와 동일하게 "원문의 감성 그대로" 라고 정해지기 전이라 약간의 의역을 포함하였던 부분인데, "Dockerfile은 작성하고자하는 이미지에 대한 구성요소를 미리 설정해놓은 파일입니다" 으로 변경합니다.

2018-09-03 02:36 UTC, lawlait commented on content/ko/docs/tutorials/hello-minikube.md
> +이제 Minikube 컨텍스트를 설정하십시오. 컨텍스트는 `kubectl` 과 상호 작용하는
네.. 상호작용이라는 말을 잘 안쓰다보니 뭔가 좋은 게 없을까 고민하다가 보니 문장 자체가 이상해진 것 같습니다.
@zer0big 감사드립니다.

2018-09-03 03:54 UTC, lawlait commented
말씀 주신 사항들 수정하였고, 논란이 될 만한 부분은 점차 수정하겠습니다.
@ClaudiaJKang 감사합니다.

2018-09-04 01:02 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
> +작성된 애플리케이션 실행:
보통 객관적인 정보를 전달하는 글은 정확한 정보 전달을 목적으로 하므로 정보의 왜곡 가능성이 높은 의역보다는 직역을 선호합니다. 쿠버네티스 문서도 같은 성격이므로 회의에서 그 점을 재확인했습니다. 

하지만 절대적인 규칙으로 받아들이시는 것 같아서 커멘트 드립니다. 때로는 한국어로 자연스러운 의역이 어색한 번역체가 되는 직역보다 나을 수 있으니, 자신있다면 의역하셔도 됩니다.

2018-09-04 14:41 UTC, gochist commented
@lawlait 오늘 회의에서 평어체를 기준으로 하기로 했습니다. 본 PR에서 해당 기준을 적용해주실 수 있을까요? 아니면 본 PR이 Merge된 후에 문체 변경을 위한 이슈를 따로 등록하겠습니다.

2018-09-18 13:47 UTC, ClaudiaJKang commented
/lgtm
/approve

2018-09-18 13:48 UTC, ianychoi commented
/lgtm

Let's merge and change comments later to move forward with branch strategy suggested by @gochist

2018-09-18 13:55 UTC, ClaudiaJKang commented
/hold cancel

2018-09-18 13:56 UTC, merged