Translate tutorials/kubernetes-basics/expose in Korean
kubernetes/kubernetes-docs-ko pull request #25
Opened 2018-08-31 05:24 UTC by zer0big

요청하신 Sync 처리 후 다시 PR 요청 드립니다.

2018-08-31 05:57 UTC, zer0big commented
/assign @gochist

2018-08-31 07:04 UTC, gochist commented
@zer0big 
감사합니다! 다음 파일을 PR에서 빼주시면 리뷰를 시작하겠습니다.
```
content/ko/docs/home/expose-interactive.html
content/ko/docs/home/expose-intro.html
```

2018-08-31 07:41 UTC, zer0big commented
@gochist 
두 파일 제거 반영했는데 요청하신 사항대로 처리 된건지 확인 부탁 드려요~

2018-08-31 14:23 UTC, gochist requested changes
참고를 부탁드린 리뷰는 말 그대로 머지의 필수 조건이 아닙니다. 내용이 많지만 반영 부탁드립니다. 수정이 완료되면 단일 커밋으로 squash를 요청드리겠습니다.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/_index.md
> +title: 여러분의 앱을 퍼블릭으로 노출하기
한국어는 주어가 겉으로 많이 드러나지 않는 언어라 번역 시 주어를 생략하는 편이 자연스러운 경우가 많습니다. 이대로도 의미는 통하므로 괜찮지만 저는 "여러분의" 를 생략하기를 권해드립니다. 참고해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/_index.md
> +title: 여러분의 앱을 퍼블릭으로 노출하기
저는 #24 에서 "외부로"로 옮겼습니다. 참고해주세요. 원문의 다른 부분에 아래와 같은 문장도 있는데 같은 의미이기 때문입니다.  
> Expose an application outside a Kubernetes cluster using a Service

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +					<li>레이블들과 레이블셀랙터 객체들이 어떻게 서비스와 연관되는지 이해한다.</li>
현재 용어집 기준 "객체"는 "오브젝트"로 변경해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +					<li>레이블들과 레이블셀랙터 객체들이 어떻게 서비스와 연관되는지 이해한다.</li>
복수형은 내용 상 중요하지 않은 경우 단수로 옮기는 것이 더 자연스럽습니다. 특히 아래에 나오는 "서비스들과 레이블들" 이라는 제목은 눈에 띄게 번역체입니다. 참고해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +                <a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/scale-intro/" role="button">모듈 5에서 계속하기<span class="btn__next">›</span></a>
저는 "모듈 X로 진행하기"로 옮겼습니다. 참고해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스 <a href="/docs/concepts/workloads/pods/pod-overview/">파드들</a> 은 언젠가는 죽게된다. 실제 파드들은  <a href="/docs/concepts/workloads/pods/pod-lifecycle/">생명주기</a>를 갖는다. 워커 노드가 죽으면, 노드 상에서 동작하는 파드들 또한 종료
원문이 가로 폭을 기준으로 강제 개행한 경우 옮길 때도 같은 기준으로 개행을 해주는 것이 추후 변경 추적, 관리에 편리합니다. 참고해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스 <a href="/docs/concepts/workloads/pods/pod-overview/">파드들</a> 은 언젠가는 죽게된다. 실제 파드들은  <a href="/docs/concepts/workloads/pods/pod-lifecycle/">생명주기</a>를 갖는다. 워커 노드가 죽으면, 노드 상에서 동작하는 파드들 또한 종료
용어집에 따라 "A ReplicationController"는 "레플리케이션 컨트롤러"로 옮겨주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스 <a href="/docs/concepts/workloads/pods/pod-overview/">파드들</a> 은 언젠가는 죽게된다. 실제 파드들은  <a href="/docs/concepts/workloads/pods/pod-lifecycle/">생명주기</a>를 갖는다. 워커 노드가 죽으면, 노드 상에서 동작하는 파드들 또한 종료
한국어는 세미콜론을 문장부호로 사용하지 않습니다. 문맥에 맞게 "그래서" 또는 "왜냐하면"의 의미로 옮겨주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스 <a href="/docs/concepts/workloads/pods/pod-overview/">파드들</a> 은 언젠가는 죽게된다. 실제 파드들은  <a href="/docs/concepts/workloads/pods/pod-lifecycle/">생명주기</a>를 갖는다. 워커 노드가 죽으면, 노드 상에서 동작하는 파드들 또한 종료
s/갖으며/가지며/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스 <a href="/docs/concepts/workloads/pods/pod-overview/">파드들</a> 은 언젠가는 죽게된다. 실제 파드들은  <a href="/docs/concepts/workloads/pods/pod-lifecycle/">생명주기</a>를 갖는다. 워커 노드가 죽으면, 노드 상에서 동작하는 파드들 또한 종료
s/대체가능/대체 가능/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스에서 서비스는 하나의 논리적인 파드세트들과 그 파드들에 접근할 수 있는 정책을 정의하는 추상적 개념이다. 서비스는 독립적인 파드들 사이를 느슨하게 결합되도록 해준다. 서비스는 모든 쿠버네티스 오브젝트들과 같이 YAML <a href="/docs/concepts/configuration/overview/#general-config-tip
"파드세트들"이 여러 번 나오는데, 띄어쓰기 해주시고, 원문에서 set은 단수입니다. "파드 세트" 또는 "파드의 집합"으로 고쳐주세요. 꼭 복수형을 유지하고자 하신다면 "파드들의 집합"도 괜찮습니다.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스에서 서비스는 하나의 논리적인 파드세트들과 그 파드들에 접근할 수 있는 정책을 정의하는 추상적 개념이다. 서비스는 독립적인 파드들 사이를 느슨하게 결합되도록 해준다. 서비스는 모든 쿠버네티스 오브젝트들과 같이 YAML <a href="/docs/concepts/configuration/overview/#general-config-tip
"독립적인"은 원문과 반대의 의미입니다.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스에서 서비스는 하나의 논리적인 파드세트들과 그 파드들에 접근할 수 있는 정책을 정의하는 추상적 개념이다. 서비스는 독립적인 파드들 사이를 느슨하게 결합되도록 해준다. 서비스는 모든 쿠버네티스 오브젝트들과 같이 YAML <a href="/docs/concepts/configuration/overview/#general-config-tip
preferred 번역해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스에서 서비스는 하나의 논리적인 파드세트들과 그 파드들에 접근할 수 있는 정책을 정의하는 추상적 개념이다. 서비스는 독립적인 파드들 사이를 느슨하게 결합되도록 해준다. 서비스는 모든 쿠버네티스 오브젝트들과 같이 YAML <a href="/docs/concepts/configuration/overview/#general-config-tip
동사 "정의하다"의 활용입니다. 붙여써주세요. 피동 표현의 중복도 고쳐주세요.
s/정의 되어진다/정의된다/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스에서 서비스는 하나의 논리적인 파드세트들과 그 파드들에 접근할 수 있는 정책을 정의하는 추상적 개념이다. 서비스는 독립적인 파드들 사이를 느슨하게 결합되도록 해준다. 서비스는 모든 쿠버네티스 오브젝트들과 같이 YAML <a href="/docs/concepts/configuration/overview/#general-config-tip
피동 표현의 중복입니다.
s/결정되어 진다/결정된다/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스에서 서비스는 하나의 논리적인 파드세트들과 그 파드들에 접근할 수 있는 정책을 정의하는 추상적 개념이다. 서비스는 독립적인 파드들 사이를 느슨하게 결합되도록 해준다. 서비스는 모든 쿠버네티스 오브젝트들과 같이 YAML <a href="/docs/concepts/configuration/overview/#general-config-tip
참고해주세요. 아래가 더 자연스러울 것 같습니다.
s/스펙 내에 selector 포함 없이 서비스를/스펙에 selector가 포함되지 않은 서비스를/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스에서 서비스는 하나의 논리적인 파드세트들과 그 파드들에 접근할 수 있는 정책을 정의하는 추상적 개념이다. 서비스는 독립적인 파드들 사이를 느슨하게 결합되도록 해준다. 서비스는 모든 쿠버네티스 오브젝트들과 같이 YAML <a href="/docs/concepts/configuration/overview/#general-config-tip
수동문을 능동문으로 바꿔주면 보다 자연스러운 번역이 되는 경우가 많다고 합니다. 참고해주세요.
s/서비스에 의해 대상으로 선정된/서비스가 대상으로 하는/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>비록 각 파드들이 고유의 IP를 갖고 있기는 하지만, 그 IP들은 서비스의 도움없이 클러스터 외부로 노출되어질 수 없다. 서비스들은 여러분의 애플리케이션들에게 트래픽이 실릴 수 있도록 허용해준다. 서비스들은 ServiceSpec 에서 <code>type</code>을 지정함으로써 다양한 방식들로 노출시킬 수 있다:</p>
피동 표현의 중복입니다.
s/노출되어질/노출될/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>비록 각 파드들이 고유의 IP를 갖고 있기는 하지만, 그 IP들은 서비스의 도움없이 클러스터 외부로 노출되어질 수 없다. 서비스들은 여러분의 애플리케이션들에게 트래픽이 실릴 수 있도록 허용해준다. 서비스들은 ServiceSpec 에서 <code>type</code>을 지정함으로써 다양한 방식들로 노출시킬 수 있다:</p>
영어와 한국어의 문장부호 : 의 용도가 달라서 번역 시 생략해도 되는 경우가 많습니다. 참고해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>NodePort</i> - NAT가 이용되는 클러스터 내에서 각각 선택된 Node들의 동일한 포트에 서비스를 노출시켜준다. <code>&lt;NodeIP&gt;:&lt;NodePort&gt;</code>를 이용하여 클러스터 외부로부터 서비스가 접근가능토록 해준다. CluserIP의 상위집합 이다.</li>
아래와 같이 변경하면 더 자연스러울 것 같습니다. 원문도 피동 표현이 아닙니다. 참고해주세요.
s/NAT가 이용되는/NAT를 이용해서/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>NodePort</i> - NAT가 이용되는 클러스터 내에서 각각 선택된 Node들의 동일한 포트에 서비스를 노출시켜준다. <code>&lt;NodeIP&gt;:&lt;NodePort&gt;</code>를 이용하여 클러스터 외부로부터 서비스가 접근가능토록 해준다. CluserIP의 상위집합 이다.</li>
용어집 기준 맞춰주세요.
s/Node/노드/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>NodePort</i> - NAT가 이용되는 클러스터 내에서 각각 선택된 Node들의 동일한 포트에 서비스를 노출시켜준다. <code>&lt;NodeIP&gt;:&lt;NodePort&gt;</code>를 이용하여 클러스터 외부로부터 서비스가 접근가능토록 해준다. CluserIP의 상위집합 이다.</li>
띄어쓰기 맞춰주세요.
s/상위집합 이다/상위 집합이다/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>LoadBalancer</i> - (지원 가능한 경우) 기존 클라우드에서 외부용 로드밸런서를 생성하고 서비스에 고정된 공인 IP를 할당해준다. NodePort의 상위집합 이다. </li>
띄어쓰기 맞춰주세요.
s/상위집합 이다/상위 집합이다/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>ExternalName</i> - 이름으로 CNAME 레코드를 반환함으로써 임의의 이름(스펙에서 <code>externalName</code>으로 명시)을 이용하여 서비스를 노출시켜준다. 프록시는 사용되지 않는다. 이 방식은 code>kube-dns</code> 버전 1.7 이상에서 지원 가능하다.</li>
원문의 "v1.7" 은 그대로 옮겨도 될 것 같습니다. 참고해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>부가적으로, spec에 <code>selector</code>를 정의하지 않고 말아넣은 서비스들의 몇 가지 유즈케이스들이 있음을 주의하자. <code>selector</code> 없이 생성된 서비스는 상응하는 엔드포인트 객체들 또한 생성하지 않는다. 이로써 사용자들로 하여금 하나의 서비스를 특정한 엔드포인트에 매핑 시킬수 있도록 해준다. sel
위에서는 유사한 맥락에서 한글로 표기했습니다. 일관성을 맞춰주세요.
s/spec/스펙/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>부가적으로, spec에 <code>selector</code>를 정의하지 않고 말아넣은 서비스들의 몇 가지 유즈케이스들이 있음을 주의하자. <code>selector</code> 없이 생성된 서비스는 상응하는 엔드포인트 객체들 또한 생성하지 않는다. 이로써 사용자들로 하여금 하나의 서비스를 특정한 엔드포인트에 매핑 시킬수 있도록 해준다. sel
참고해주세요. 명사 use는 "유스"로 표기합니다.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>부가적으로, spec에 <code>selector</code>를 정의하지 않고 말아넣은 서비스들의 몇 가지 유즈케이스들이 있음을 주의하자. <code>selector</code> 없이 생성된 서비스는 상응하는 엔드포인트 객체들 또한 생성하지 않는다. 이로써 사용자들로 하여금 하나의 서비스를 특정한 엔드포인트에 매핑 시킬수 있도록 해준다. sel
s/객체/오브젝트/ by 용어집

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>부가적으로, spec에 <code>selector</code>를 정의하지 않고 말아넣은 서비스들의 몇 가지 유즈케이스들이 있음을 주의하자. <code>selector</code> 없이 생성된 서비스는 상응하는 엔드포인트 객체들 또한 생성하지 않는다. 이로써 사용자들로 하여금 하나의 서비스를 특정한 엔드포인트에 매핑 시킬수 있도록 해준다. sel
"manually" 번역이 누락되었습니다.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +					<h3>요약y</h3>
s/요약y/요약/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +						<li>여러 파드들 사이로 트래픽 로드밸런싱 하기</li>
의견입니다. 참고해주세요. 
s/여러 파드들 사이로/여러 파드에 걸쳐서/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 파드세트들 사이에서 트래픽을 라우트한다. 여러분의 애플리케이션에 영향을 주지 않으면서 쿠버네티스에서 파드들이 죽게도 하고, 복제가 되게도 해주는 추상적 개념이다. 독립적인 파드들 사이에서의 디스커버리와 라우팅은 (하나의 애플리케이션에서 프로트엔드와 백엔드 컴포넌트와 같은) 쿠버네티스 서비스들에 의해 처리된다.</p>
"across"를 "사이에서"로 옮기는 것 보다 "~에 걸쳐서"로 옮기는게 더 자연스러울 것 같습니다. 참고해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 파드세트들 사이에서 트래픽을 라우트한다. 여러분의 애플리케이션에 영향을 주지 않으면서 쿠버네티스에서 파드들이 죽게도 하고, 복제가 되게도 해주는 추상적 개념이다. 독립적인 파드들 사이에서의 디스커버리와 라우팅은 (하나의 애플리케이션에서 프로트엔드와 백엔드 컴포넌트와 같은) 쿠버네티스 서비스들에 의해 처리된다.</p>
"독립적인"은 원문 내용과 반대의 의미입니다.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 쿠버네티스의 객체들에 대해 논리적 운영을 허용해주는 원시적인 하나의 그룹핑인, <a href="/docs/concepts/overview/working-with-objects/labels">labels and selectors</a>를 이용하여 파드세트들과 매치시킨다. 레이블들은 오브젝트들에 붙여진 키/밸류 쌍으로 다양한 방식으로 이
"labels and selectors" 번역해주세요.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 쿠버네티스의 객체들에 대해 논리적 운영을 허용해주는 원시적인 하나의 그룹핑인, <a href="/docs/concepts/overview/working-with-objects/labels">labels and selectors</a>를 이용하여 파드세트들과 매치시킨다. 레이블들은 오브젝트들에 붙여진 키/밸류 쌍으로 다양한 방식으로 이
레이블은 운영의 대상이 아니라 연산의 대상입니다.
s/논리적 운영/논리 연산/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 쿠버네티스의 객체들에 대해 논리적 운영을 허용해주는 원시적인 하나의 그룹핑인, <a href="/docs/concepts/overview/working-with-objects/labels">labels and selectors</a>를 이용하여 파드세트들과 매치시킨다. 레이블들은 오브젝트들에 붙여진 키/밸류 쌍으로 다양한 방식으로 이
s/객체/오브젝트/ by 용어집

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 쿠버네티스의 객체들에 대해 논리적 운영을 허용해주는 원시적인 하나의 그룹핑인, <a href="/docs/concepts/overview/working-with-objects/labels">labels and selectors</a>를 이용하여 파드세트들과 매치시킨다. 레이블들은 오브젝트들에 붙여진 키/밸류 쌍으로 다양한 방식으로 이
동사 "가능하다"의 활용입니다. 띄어쓰기 맞춰주세요.
s/이용가능 하다/이용 가능하다/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 쿠버네티스의 객체들에 대해 논리적 운영을 허용해주는 원시적인 하나의 그룹핑인, <a href="/docs/concepts/overview/working-with-objects/labels">labels and selectors</a>를 이용하여 파드세트들과 매치시킨다. 레이블들은 오브젝트들에 붙여진 키/밸류 쌍으로 다양한 방식으로 이
원문의 Primitive는 명사로 활용됐습니다. 수정해주세요.

s/원시적인 하나의 그룹핑인/그룹핑 프리미티브인/ 
또는
s/원시적인 하나의 그룹핑인/기본 그룹핑 단위인/ 
를 제안드립니다.

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/expose-interactive/" role="button">대화형 강좌 시작<span class="btn__next">›</span></a>
문서 내 일관성 맞춰주세요.
s/강좌/튜토리얼/

2018-08-31 14:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>레이블들은 생성 시점 또는 이후 시점에 붙여질 수 있다. 언제든지 수정이 가능하다. 이제 서비스를 이용하여 우리의 애플리케이션을 노출도 시켜보고 레이블들도 적용해 보자.</p>
원문의 object가 누락되었습니다.
s/생성 시점/오브젝트의 생성 시점/

2018-08-31 14:52 UTC, zer0big commented on content/ko/docs/tutorials/kubernetes-basics/expose/_index.md
> +title: 여러분의 앱을 퍼블릭으로 노출하기
넵, 리뷰 주신대로 반영하겠습니다.

2018-08-31 14:53 UTC, zer0big commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +					<li>레이블들과 레이블셀랙터 객체들이 어떻게 서비스와 연관되는지 이해한다.</li>
넵, 수정하겠습니다.

2018-08-31 14:54 UTC, zer0big commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +                <a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/scale-intro/" role="button">모듈 5에서 계속하기<span class="btn__next">›</span></a>
넵, 일치시키겠습니다.

2018-08-31 14:56 UTC, zer0big commented
@gochist 리뷰 감사드립니다~ 리뷰주신 사항 반영하도록 하겠습니다.

2018-09-01 01:08 UTC, zer0big commented
@gochist 리뷰해주신 내용 모두 좋아 모두 반영했습니다. 감사합니다. 다만 개행관련 부분은 제가 정확하게 이해를 못해 패스했습니다.

2018-09-01 02:12 UTC, gochist requested changes
빠른 수정 감사드립니다! 일부 리뷰 결과 반영이 누락된 내용이 있습니다. 추가 변경 요청 사항도 있습니다.

개행 관련 내용은 원문에 강제 개행이 있는 것으로 제가 착각했습니다. 무시해주세요. ( #11 에서 실수 또는 의도적으로 강제 개행이 추가된 것 같습니다. )

2018-09-01 02:12 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +			<p>쿠버네티스 <a href="/docs/concepts/workloads/pods/pod-overview/">파드들</a> 은 언젠가는 죽게된다. 실제 파드들은  <a href="/docs/concepts/workloads/pods/pod-lifecycle/">생명주기</a>를 갖는다. 워커 노드가 죽으면, 노드 상에서 동작하는 파드들 또한 종료
s/A 레플리케이션/레플리케이션/

2018-09-01 02:12 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>NodePort</i> - NAT가 이용되는 클러스터 내에서 각각 선택된 Node들의 동일한 포트에 서비스를 노출시켜준다. <code>&lt;NodeIP&gt;:&lt;NodePort&gt;</code>를 이용하여 클러스터 외부로부터 서비스가 접근가능토록 해준다. CluserIP의 상위집합 이다.</li>
이 문단의 리뷰 반영이 누락되었습니다.

2018-09-01 02:12 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>LoadBalancer</i> - (지원 가능한 경우) 기존 클라우드에서 외부용 로드밸런서를 생성하고 서비스에 고정된 공인 IP를 할당해준다. NodePort의 상위집합 이다. </li>
이 문단도 리뷰 반영이 누락되었습니다.

2018-09-01 02:12 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<li><i>ExternalName</i> - 이름으로 CNAME 레코드를 반환함으로써 임의의 이름(스펙에서 <code>externalName</code>으로 명시)을 이용하여 서비스를 노출시켜준다. 프록시는 사용되지 않는다. 이 방식은 code>kube-dns</code> 버전 1.7 이상에서 지원 가능하다.</li>
> 이 방식은 code>kube-dns</code>

"<" 이 누락되어 페이지 렌더링시 마크업 태그가 노출됩니다. "code>"

2018-09-01 02:18 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>서비스는 쿠버네티스의 객체들에 대해 논리 연산을 허용해주는 기본 그룹핑 단위인, <a href="/docs/concepts/overview/working-with-objects/labels">레이블과 셀렉터s</a>를 이용하여 파드 세트와 매치시킨다. 레이블들은 오브젝트들에 붙여진 키/밸류 쌍으로 다양한 방식으로 이용 가능하다:</p>
s/셀렉터s/셀렉터/

2018-09-01 02:51 UTC, zer0big commented
@gochist 리뷰해주신 내용 너무 감사드리고, 자체적으로 재리뷰한 결과 반영 하였습니다~(다시 보니 그래도 수정사항이 보이더군요^^)

2018-09-01 05:27 UTC, gochist approved these changes

2018-09-01 05:29 UTC, closed without merging

2018-09-01 05:36 UTC, gochist commented
@zer0big 죄송합니다. 제가 조작을 잘못해서 PR이 close 되었는데, 곧 조치하겠습니다.