[Setup] page's header and sub header translate into Korean.
kubernetes/kubernetes-docs-ko pull request #33
Opened 2018-09-09 05:19 UTC by ClaudiaJKang

**#8 [Setup] Setup page's header and sub header translate into Korean.**
  - [X] [1. _index](https://kubernetes.io/docs/setup) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/_index.md)
  - [X] [2. independent/_index](https://kubernetes.io/docs/setup/independent) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/independent/_index.md)
  - [X] [3. turnkey/_index](https://kubernetes.io/docs/setup/turnkey) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/turnkey/_index.md)
  - [X] [4. on-premises-vm/_index](https://kubernetes.io/docs/setup/on-premises-vm) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/on-premises-vm/_index.md)
  - [X] [5. custom-cloud/_index](https://kubernetes.io/docs/setup/custom-cloud) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/custom-cloud/_index.md)
  - [X] [6. Building Large Clusters](https://kubernetes.io/docs/setup/cluster-large) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/cluster-large.md)
  - [X] [7. Building from Source](https://kubernetes.io/docs/setup/building-from-source) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/building-from-source.md)
  - [X] [10. Picking the Right Solution](https://kubernetes.io/docs/setup/pick-right-solution) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/pick-right-solution.md)

2018-09-10 01:07 UTC, gochist requested changes
검토 의견 드립니다. 몇 가지 수정 부탁드립니다.

2018-09-10 01:07 UTC, gochist commented on content/ko/docs/setup/_index.md
> +title: 설정
s/설정/설치/ or s/설정/구축/

본 탭 이하 문서의 내용은 모두 쿠버네티스의 설치나 구축을 주제로 다루고 있습니다. 설정은 이미 설치된 소프트웨어의 세부 항목을 조정하는 의미로 받아들여질 수 있습니다.

2018-09-10 01:07 UTC, gochist commented on content/ko/docs/setup/building-from-source.md
> +title: 소스로 구성
s/소스로 구성/소스로부터 빌드/ 

소스 코드로부터 실행 가능한 형태의 산출물을 얻는 과정 또는 결과물을 '빌드'라고 합니다. "소스로부터 빌드"로 변경해주세요. 아래에도 반복되는데 모두 수정해주세요.

2018-09-10 01:07 UTC, gochist commented on content/ko/docs/setup/cluster-large.md
> +title: 대형 클러스터 구성
s/구성/구축/

같은 영단어라도 맥락에 따라 다르게 옮겨야하겠습니다. Build의 경우, '소스를 빌드하다', '클러스터를 구축하다'가 어울립니다. 클러스터의 구성 요소를 살펴본다는 의미로 오해할 여지가 있겠습니다.

2018-09-10 01:07 UTC, gochist commented on content/ko/docs/setup/custom-cloud/_index.md
> +title: 사용자 지정 클라우드 솔루션
이대로도 괜찮지만, 개인적으로 "맞춤형"이나 "커스텀"을 선호합니다. 참고해주세요.

2018-09-10 01:07 UTC, gochist commented on content/ko/docs/setup/pick-right-solution.md
> +# Turnkey 클라우드 솔루션
s/Turnkey/턴키/

[외래어로 심의](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=61&qna_seq=121797)된 단어입니다. 이하 모두 수정 바랍니다.

2018-09-15 05:07 UTC, ClaudiaJKang commented
@gochist 리뷰 감사합니다. 리뷰해주신 내용 반영하였습니다. 

다만 `Custom Cloud`의 경우 기타 참고 용어집 중 하나인 [Microsoft 언어 포털](https://www.microsoft.com/en-us/language)에서는 [`사용자 지정`](https://www.microsoft.com/ko-kr/language/Search?&searchTerm=Custom%20Cloud%20Solutions%09&langID=%ED%95%9C%EA%B5%AD%EC%96%B4&Source=true&productid=%EB%AA%A8%EB%93%A0%20%EC%A0%9C%ED%92%88)으로 정의하고 있기에 `사용자 지정`으로 번역하는 것으로 유지하겠습니다.

2018-09-15 08:46 UTC, gochist approved these changes

2018-09-15 08:47 UTC, gochist commented
/lgtm
/approve

2018-09-15 08:49 UTC, merged