Translate tutorials/kubernetes-basics/update in Korean
kubernetes/kubernetes-docs-ko pull request #35
Opened 2018-09-11 01:40 UTC by zer0big

커밋/히스토리 정제하여 다시 요청드립니다.
tutorial-kubernetes-basics-update에 대한 한글 번역본 초안입니다.

2018-09-12 14:06 UTC, gochist reviewed
지난 리뷰와 같이 참고를 부탁드린 내용은 선택적으로 반영하시면 되겠습니다.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p> 사용자들은 애플리케이션이 항상 이용가능한 상태일 것이라 여기고 개발자들은 하루에 여러번씩 새로운 버전을
s/이용가능/이용 가능/ or s/이용가능/가용/

띄어쓰기 필요합니다. "가용한"도 괜찮습니다. 이하 일괄 적용 바랍니다.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    새로운 파드는 이용가능한 자원을 보유한 노드를 대상으로 스케쥴 되어질 것이다.</p>
s/스케쥴 되어질/스케줄될/

['스케줄'로 심의된 외래어](https://www.korean.go.kr/front/foreignSpell/foreignSpellView.do?mn_id=96&forgn_seq=10881&pageIndex=1)입니다. 피동 표현의 중복도 제거해주세요.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    새로운 파드는 이용가능한 자원을 보유한 노드를 대상으로 스케쥴 되어질 것이다.</p>
s/노드를 대상으로/노드로/

보다 간결한 표현을 선호합니다. 참고해주세요.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>애플리케이션 스케일링과 유사하게, 디플로이먼트가 외부로 노출되어 지면, 서비스는 업데이트가 이루어 지는 동안 오직 이용가능한 파드에게만 트래픽을 로드밸런스 할 것이다. 이용가능한 파드란 애플리케이션의 사용자들에게 이용가능한 상태의 인스턴스를 말한다.</p>
s/노출되어 지면/노출되면/

피동 표현의 중복입니다. 이하 일괄 적용 바랍니다.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    <li>하나의 환경에서 또 다른 환경으로의 애플리케이션 증진 (컨테이너 이미지 업데이트를 통해)</li>
s/증진/프로모션/

개발 환경에서 스테이징 환경으로 또는 스테이징 환경에서 운영 환경으로 애플리케이션을 프로모션한다는 의미인데, 한국어로 적절한 단어를 찾기 어렵네요. 증진은 전하고자 하는 의미와 차이가 큰 것 같습니다. 참고해주세요.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>애플리케이션 스케일링과 유사하게, 디플로이먼트가 외부로 노출되어 지면, 서비스는 업데이트가 이루어 지는 동안 오직 이용가능한 파드에게만 트래픽을 로드밸런스 할 것이다. 이용가능한 파드란 애플리케이션의 사용자들에게 이용가능한 상태의 인스턴스를 말한다.</p>
s/이루어 지는/이루어지는/

"이루다"와 "(~어)지다"의 합성어로 붙여씁니다. 이하 일괄 적용 바랍니다.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>이전 모듈에서 여러 개의 인스턴스를 동작시키도록 애플리케이션을 스케일 했다. 이것은 애플리케이션의 가용성에 영향을 미치지 않으면서
s/스케일 했다/스케일했다/

[외래어+하다](http://www.korean.go.kr/front/onlineQna/onlineQnaView.do;front=E98B5D73E3F48BC7F2674D9062DF65F7?mn_id=61&qna_seq=14358&pageIndex=1)의 경우 붙여서 씁니다.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                   업데이트를 수행하는 것에 대한 요구이다. 기본적으로, 업데이트가 이루어지는 동안 이용불가한 파드의 최대 갯수와 생성가능한 새로운 파드의 최대 갯수는 같다.
s/같다/하나다/ or s/같다/한 개다/

기본 값이 1 이라는 의미입니다.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                   업데이트를 수행하는 것에 대한 요구이다. 기본적으로, 업데이트가 이루어지는 동안 이용불가한 파드의 최대 갯수와 생성가능한 새로운 파드의 최대 갯수는 같다.
s/갯수/개수/

[개수가 바른 표기입니다.](http://www.korean.go.kr/front/mcfaq/mcfaqView.do;front=C548CDB1FB9D36A5DFBB2303CD31CD10?mn_id=62&mcfaq_seq=3096&pageIndex=1)

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                   두 옵션은 (파드에 대한) 숫자 또는 백분율로 구성되어질 수 있다.
s/구성되어질/구성될/ 

중복 피동 표현입니다.  

또는,

s/구성되어질/설정할/

개인적으로 해당 단어를 '설정하다'로 옮기는 편을 선호합니다. 사람이 주체로 쓰이는 편을 선호하는 우리말의 특성 상, 가능한 능동 표현이 더 자연스럽습니다. 참고해주세요.

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                   업데이트를 수행하는 것에 대한 요구이다. 기본적으로, 업데이트가 이루어지는 동안 이용불가한 파드의 최대 갯수와 생성가능한 새로운 파드의 최대 갯수는 같다.
s/생성가능한/생성 가능한/

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                   업데이트를 수행하는 것에 대한 요구이다. 기본적으로, 업데이트가 이루어지는 동안 이용불가한 파드의 최대 갯수와 생성가능한 새로운 파드의 최대 갯수는 같다.
s/이용불가한/이용 불가한/

2018-09-12 14:06 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                   두 옵션은 (파드에 대한) 숫자 또는 백분율로 구성되어질 수 있다.
s/숫자/개수/

숫자도 괜찮지만, 파드의 개수로도 설정할 수 있다는 의미를 보다 명확히 전달하기 위함입니다. 파드의 숫자라고 표현하면 파드를 대표하는 속성으로 오해할 여지가 있습니다. 참고해주세요.

2018-09-12 14:21 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    쿠버네티스에서, 업데이트는 버전으로 관리되고 어떠한 디플로이먼트 업데이트라도 이전의 상태로 (안정적인) 원복이 가능하다.</p>
s/상태로 (안정적인)/(안정적인) 버전으로/

stable이 version을 꾸며주고 있습니다. 참고해주세요.

2018-09-12 14:32 UTC, zer0big commented
@gochist 리뷰 감사드립니다. 전체적으로 공감이 확확 됩니다. 업데이트 하도록 하겠습니다~

2018-09-13 14:25 UTC, gochist reviewed
반영이 안된 내용이 있어 한 번 더 작업 요청드립니다.

2018-09-13 14:25 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    새로운 파드는 가용한 자원을 보유한 노드로 스케줄 되어질 것이다.</p>
s/스케줄 되어질/스케줄될/

피동 표현의 중복 제거

2018-09-13 14:25 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>애플리케이션 스케일링과 유사하게, 디플로이먼트가 외부로 노출되면, 서비스는 업데이트가 이루어 지는 동안 오직 가용한 파드에게만 트래픽을 로드밸런스 할 것이다. 가용한 파드란 애플리케이션의 사용자들에게 가용한 상태의 인스턴스를 말한다.</p>
s/이루어 지는/이루어지는/

"이루다"와 "(~어)지다"의 합성어로 붙여씁니다. 이하 일괄 적용 바랍니다.

2018-09-13 14:25 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    <p><i>디플로이먼트가 외부로 노출되면, 서비스는 업데이트가 이루어 지는 동안 오직 가용한 파드에게만 트래픽을 로드밸런스 할 것이다. </i></p>
s/이루어 지는/이루어지는/

"이루다"와 "(~어)지다"의 합성어로 붙여씁니다.

2018-09-13 14:25 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                   업데이트를 수행하는 것에 대한 요구이다. 기본적으로, 업데이트가 이루어지는 동안 이용 불가한 파드의 최대 개수와 생성 가능한 새로운 파드의 최대 개수는 같다.
s/같다/하나다/ or s/같다/한 개다/

기본 값이 1 이라는 의미입니다.

2018-09-17 10:32 UTC, ClaudiaJKang commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +<<<<<<< HEAD
git 수정 과정에서 수정 버전이 꼬인듯 합니다. 
현재라인 `<<<<<<< HEAD` 부터 아래 35라인 `>>>>>>> 06d9d8ec9...`까지 두 가지 내용 중 최신 버전의 내용으로만 수정이 필요합니다.

2018-09-17 10:59 UTC, gochist requested changes
감사합니다! 리뷰 반영해주시면 제가 단일 커밋으로 Squash 해서 Merge할 수 있도록 하겠습니다.

2018-09-17 10:59 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>이전 모듈에서 여러 개의 인스턴스를 동작시키도록 애플리케이션을 스케일 했다. 이것은 애플리케이션의 가용성에 영향을 미치지 않으면서
@zer0big 조치 바랍니다.

2018-09-17 10:59 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +<<<<<<< HEAD
아래 라인(06d9d8ec9...) 선택해주세요.

2018-09-18 04:23 UTC, gochist commented on content/ko/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>이전 모듈에서 여러 개의 인스턴스를 동작시키도록 애플리케이션을 스케일 했다. 이것은 애플리케이션의 가용성에 영향을 미치지 않으면서
s/스케일 했다/스케일했다/

외래어+하다의 경우 붙여서 씁니다. 조치 바랍니다.

2018-09-18 04:31 UTC, gochist commented
/lgtm

2018-09-18 04:31 UTC, gochist approved these changes

2018-09-18 04:32 UTC, merged