Update translation on tutorials/hello-minikube.md
kubernetes/kubernetes-docs-ko pull request #45
Opened 2018-09-27 16:01 UTC by gochist

fixes #43

2018-09-29 04:49 UTC, ianychoi requested changes
Only one `deployment` is my request change and the others are questions or suggestions. Please see my comment.

2018-09-29 04:49 UTC, ianychoi commented on content/ko/docs/tutorials/hello-minikube.md
> +  **참고:** macOS 10.13 버전으로 업데이트 후 `brew update`를 실행 시 Homebrew에서 다음과 같은 오류가 발생할 경우에는,
"`brew update`를" - `[text]` 다음에 띄어쓰기를 적어 주는 게 렌더링에 문제가 없는 것으로 알고 있습니다. 괜찮은지요?

2018-09-29 04:49 UTC, ianychoi commented on content/ko/docs/tutorials/hello-minikube.md
> +`kubectl`이 클러스터와 통신할 수 있도록 설정되어 있는지 확인한다.
"`kubectl`이" - (ditto)

2018-09-29 04:49 UTC, ianychoi commented on content/ko/docs/tutorials/hello-minikube.md
> +브라우저에서 쿠버네티스 대시보드를 연다.
[Suggestion] "대시보드를 연다." - 원 문장에서 `:`를 사용하고 있는데, 마침표로 바꾸는 부분을 차후 회의때 다루어도 좋을 것 같습니다.

2018-09-29 04:49 UTC, ianychoi commented on content/ko/docs/tutorials/hello-minikube.md
> +개발 환경에서, `kubectl expose` 커맨드를 사용해서 파드를 퍼블릭 인터넷에
The original word was `deployment` but it wrongly translated into `개발`, which meaning is `development`

2018-09-29 08:38 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
> +  **참고:** macOS 10.13 버전으로 업데이트 후 `brew update`를 실행 시 Homebrew에서 다음과 같은 오류가 발생할 경우에는,
붙여써도 렌더링에 문제 없음을 확인했습니다.

2018-09-29 08:39 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
> +`kubectl`이 클러스터와 통신할 수 있도록 설정되어 있는지 확인한다.
위와 같습니다. :)

2018-09-29 08:40 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
> +브라우저에서 쿠버네티스 대시보드를 연다.
한국어의 문장부호 쌍점과 영어의 문장부호 콜론의 용법이 달라 대체로 옮기지 않는 것으로 알고 있습니다.

2018-09-29 08:41 UTC, gochist commented on content/ko/docs/tutorials/hello-minikube.md
> +개발 환경에서, `kubectl expose` 커맨드를 사용해서 파드를 퍼블릭 인터넷에
> From your development machine,
원문은 위와 같습니다.

2018-09-29 08:45 UTC, ianychoi commented on content/ko/docs/tutorials/hello-minikube.md
> +브라우저에서 쿠버네티스 대시보드를 연다.
네 그래서 다음 회의때 안건으로 이야기하자고 제안을 하였습니다.

2018-09-29 08:45 UTC, ianychoi commented on content/ko/docs/tutorials/hello-minikube.md
> +개발 환경에서, `kubectl expose` 커맨드를 사용해서 파드를 퍼블릭 인터넷에
앗 제가 잘못봤네요.. ㅎㅎㅎ

2018-09-29 08:45 UTC, ianychoi commented
/lgtm

2018-09-29 08:45 UTC, ianychoi approved these changes

2018-10-01 01:13 UTC, ClaudiaJKang commented
/assign
/approve

2018-10-01 01:15 UTC, merged