Setup page's header and subheader translate into Korean.
kubernetes/kubernetes-docs-ko pull request #51
Opened 2018-09-30 08:10 UTC by ClaudiaJKang

**#8 [Setup] Setup page's header and sub header translate into Korean.**
  - [ ] ~~[8. Configuring Kubernetes with Salt](https://kubernetes.io/docs/setup/salt) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/salt.md)~~ -> dev-1.12-ko.2 기준 삭제됨.
  - [X] [9. Creating a Custom Cluster from Scratch](https://kubernetes.io/docs/setup/scratch) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/scratch.md)
  - [X] [12. Running in Multiple Zones](https://kubernetes.io/docs/setup/multiple-zones) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/multiple-zones.md)
  - [X] [13. Validate Node Setup](https://kubernetes.io/docs/setup/node-conformance) | [파일](https://github.com/kubernetes/kubernetes-docs-ko/tree/dev-1.12/content/en/docs/setup/node-conformance.md)

2018-09-30 15:09 UTC, gochist requested changes
수고하셨습니다! 몇 가지만 수정 바랍니다.

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/minikube.md
> +This command shuts down the minikube virtual m학achine, but preserves all cluster state and data.
typo

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/minikube.md
> +## 비공개 컨테이너 저장소
s/비공개 컨테이너 저장소/사설 컨테이너 레지스트리/ or s/비공개 컨테이너 저장소/프라이빗 컨테이너 레지스트리/  

클라우드 서비스의 경우 1 또는 2로 많이 굳어진 것 같습니다. 컨테이너 레지스트리도 1 또는 2를 선택하는 것이 좋을 것 같습니다. 
1. 퍼블릭/프라이빗 클라우드
2. 공용/사설 클라우드
3. 공개/비공개 클라우드

또, 컨테이너와 관련해서 Registry와 Repository를 구분할 필요가 있습니다. Registry를 레지스트리, Repository를 저장소로 옮기는 것을 제안드립니다. (https://stackoverflow.com/questions/34004076/difference-between-docker-registry-and-repository 참고)

의견이니 참고해주세요.

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/minikube.md
> +## Minikube에서 HTTP 프록시 사용
"HTTP 프록시 환경에서 Minikube 사용"이 어떨까요. Minikube를 쓰는게 중요하니까요. 참고 바랍니다.

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/multiple-zones.md
> +title: 여러 지역에서 구동
클라우드에서 대개 한 Region이 여러 (Availability) Zone을 포함하는 개념을 사용합니다. 때문에 Region과 Zone을 구분할 필요가 있는데요, Region을 지역으로, Zone을 영역으로 옮기면 어떨까요. 참고 바랍니다.

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/multiple-zones.md
> +### 여러존에 파드 분배하기
"여러 존에" 띄어쓰기 해주세요. (변경 바랍니다.)
Zone은 클라우드 도메인에서 사용하는 개념이므로 일관성있게 옮기는 것이 좋겠습니다.  (참고 바랍니다,)

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/node-conformance.md
> +title: 유효한 노드 설치
s/유효한 노드 설치/노드 설치 검증하기/

validate가 동사로 사용되었습니다.

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/scratch.md
> +title: Scratch로 사용자 지정 클러스터 생성
"from scratch"는 "맨 처음부터", "아무것도 없는 상태에서부터"의 의미를 갖습니다. 변경 바랍니다.

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/scratch.md
> +#### 네트워크 정책
API Resource Object이므로 어색해도 "네트워크 폴리시"가 좋겠습니다. 하지만 네트워크 정책도 나쁘지 않습니다. 참고바랍니다.
* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#networkpolicy-v1-networking-k8s-io
* https://www.korean.go.kr/front/foreignSpell/foreignSpellView.do?mn_id=96&forgn_seq=22360&pageIndex=1

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/scratch.md
> +### 그외
띄어쓰기 필요합니다. (변경 바랍니다.)
또는, '기타'로 옮겨도 될 것 같습니다. (참고 바랍니다.)

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/scratch.md
> +### 유효한 클러스터 구동
클러스터를 확인하는 명령을 실행한다는 뜻입니다. 'validate-cluster 명령 실행'과 같이 옮겨주세요.

2018-09-30 15:09 UTC, gochist commented on content/ko/docs/setup/scratch.md
> +### Try 예제
Try도 옮겨주세요. "예제 실행해 보기"

2018-10-01 04:14 UTC, ClaudiaJKang commented
@gochist 리뷰 감사합니다. 수정했습니다.

2018-10-01 05:10 UTC, gochist commented
/lgtm
/approve

2018-10-01 05:10 UTC, gochist approved these changes

2018-10-01 05:12 UTC, merged